CREATE TABLE PERSON(
    ID IDENTITY PRIMARY KEY,
    FNAME NVARCHAR(25) NOT NULL,
    LNAME NVARCHAR(25) NOT NULL,
    GENDER NVARCHAR(4) NOT NULL, 
    AGE INT NOT NULL,
    CHECK(AGE > 0),
    SALARY DECIMAL(7, 2) NOT NULL
);
